### ISSUE TITLE
missing features from css`...`

### ISSUE THREAD

**Issue by threepointone** [threepointone/glamor#120]
- `^ $ *` attribute selectors
- custom vars, properties 
[feel free to add]

**Comment by cusxio** [comment]
I'm not too sure if this is a bug or a missing feature.

the following code:
```js
const container = css`
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    width: 100%;
    max-width: 65rem;
    margin: -4.8rem auto 0;
`;
```

produces:
```css
display: -webkit-box;
display: -moz-box;
display: -ms-flexbox;
display: -webkit-flex;
display: flex;
justify-content: center;
align-items: center;
height: 100 vh; /* notice the space after 100 */
width: 100%;
max-width: 65 rem; /* notice the space after 65 */
margin: -4 0.8 rem auto 0; /* incorrect ? */
-webkit-justify-content: center;
-webkit-align-items: center;
-ms-flex-pack: center;
-webkit-box-pack: center;
-ms-flex-align: center;
-webkit-box-align: center;
```

It works perfectly if I put quotes around the value of `max-width`, `margin`, and `height`.

i.e.

```js
const container = css`
    display: flex;
    justify-content: center;
    align-items: center;
    height: '100vh';
    width: 100%;
    max-width: '65rem';
    margin: '-4.8rem auto 0';
`;
```

**Comment by threepointone** [comment]
This looks like a bug on my end. Thanks for the catch!

**Comment by ilyabo** [comment]
Probably a related issue: 

     css`opacity: 0.5;` 

produces 

     opacity: 0 0.5;

Adding quotes around 0.5 or using ${0.5} makes it work as it should

**Comment by ilyabo** [comment]
And one more small issue with css``: 

I upgraded to 2.19.0 and now using `margin: 0;` without `px` at the end leads to an error:   

```
val.indexOf is not a function
at /Users/ilyabo/Workspace/hyperloop/vis/dashboard/node_modules/glamor/lib/css/babel.js:111:26
    at Array.forEach (native)
    at Object.Declaration (/Users/ilyabo/Workspace/hyperloop/vis/dashboard/node_modules/glamor/lib/css/babel.js:110:23)
    at convert (/Users/ilyabo/Workspace/hyperloop/vis/dashboard/node_modules/glamor/lib/css/babel.js:21:32)
    at /Users/ilyabo/Workspace/hyperloop/vis/dashboard/node_modules/glamor/lib/css/babel.js:33:14
    at Array.map (native)
    at Object.StyleSheet (/Users/ilyabo/Workspace/hyperloop/vis/dashboard/node_modules/glamor/lib/css/babel.js:32:30)
    at convert (/Users/ilyabo/Workspace/hyperloop/vis/dashboard/node_modules/glamor/lib/css/babel.js:21:32)
    at PluginPass.TaggedTemplateExpression (/Users/ilyabo/Workspace/hyperloop/vis/dashboard/node_modules/glamor/lib/css/babel.js:185:31)
    at newFn (/Users/ilyabo/Workspace/hyperloop/vis/dashboard/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/ilyabo/Workspace/hyperloop/vis/dashboard/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/ilyabo/Workspace/hyperloop/vis/dashboard/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/ilyabo/Workspace/hyperloop/vis/dashboard/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/ilyabo/Workspace/hyperloop/vis/dashboard/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/ilyabo/Workspace/hyperloop/vis/dashboard/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/ilyabo/Workspace/hyperloop/vis/dashboard/node_modules/babel-traverse/lib/context.js:192:19)
```

**Comment by threepointone** [comment]
man I just haven't done a good job with that :S I'll spend the next couple of days on fixing bugs. sorry!

**Comment by ilyabo** [comment]
Hey, it's OK. Thanks for making this awesome library!

**Comment by threepointone** [comment]
I published a new version 2.20.4 that fixes the above bugs. lemme know if you find any more!

**Comment by ilyabo** [comment]
Cool thanks!
